### ISSUE TITLE
Paths to run examples don't match local paths.

### ISSUE THREAD

**Issue by tmcgilchrist** [yminsky/incremental-tutorial#1]
A minor issue with the paths suggested for running ex2 don't match what I see locally.

https://github.com/yminsky/incremental-tutorial/blob/master/exercises/ex2.ml#L25-L28
```shell
    ./_build/exercises/main.exe server -port 8080 &
    ./_build/exercises/main.exe ex2 simple -port 8080
```

What I end up with when i build with jbuilder is an extra `default` in the path
```shell
    ./_build/default/exercises/main.exe server -port 8080 &
    ./_build/default/exercises/main.exe ex2 simple -port 8080
```

If that path sounds right I'll fix up the various comments so that they have `default` and match what I see locally.

**Comment by yminsky** [comment]
Please do. That's just a typo.

Thanks.

**Comment by tmcgilchrist** [comment]
Done https://github.com/yminsky/incremental-tutorial/pull/2
